version: "3"
services:
  logger:
    container_name: rabbit-logger
    build: ./logger
    volumes:
      - ./logger:/code
    working_dir: /code
    depends_on:
      - rabbitmq
    tty: true
  receiver:
    container_name: rabbit-receiver
    build: ./receiver
    volumes:
      - ./receiver:/code
    working_dir: /code
    depends_on:
      - rabbitmq
    tty: true
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbit-server
    hostname: rabbit
