version: "3"
services:
  producer:
    container_name: rabbit-producer
    build: ./producer
    volumes:
      - ./producer/code:/code/producer
    working_dir: /code/producer
    depends_on:
      - rabbitmq
    tty: true
  consumer:
    container_name: rabbit-consumer
    build: ./consumer
    volumes:
      - ./consumer/code:/code/consumer
    working_dir: /code/consumer
    depends_on:
      - rabbitmq
    tty: true
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbit-server
    hostname: rabbit
