version: "3"
services:
  newtask:
    container_name: rabbit-newtask
    build: ./newtask
    volumes:
      - ./newtask:/code
    working_dir: /code
    depends_on:
      - rabbitmq
    tty: true
  worker:
    container_name: rabbit-worker
    build: ./worker
    volumes:
      - ./worker:/code
    working_dir: /code
    depends_on:
      - rabbitmq
    tty: true
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbit-server
    hostname: rabbit
